# Laboratoire 4
*Algorithme PageRank de Google*


Dans ce laboratoire, vous aurez besoin de 4 notions en Python :


1.   Définir des matrices
2.   Élever une matrice à une puissance
3.   Effectuer le produit de deux matrices
4. Calculer un déterminant de matrice

Voici des exemples détaillés de ces 3 notions.



## 1. Définir des matrices

*   Vous devez d'abord **importer la librairie numpy**. Nous allons nommer cette librairie np pour simplifier la lecture du code. *Cette action doit être fait une seule fois dans tout le laboratoire.*

* Vous devez ensuite créer votre matrice à l'aide de la commande `np.array`.



Les éléments de la matrice doivent être rentrés ligne par ligne :

*   Tous les éléments d'une ligne doivent se trouver entre crochets "[ ]" et doivent être séparés par une virgule.
*   Pour changer de ligne, il suffit de fermer votre crochet, de séparer à l'aide d'une virgule et d'ouvrir un nouveau crochet pour la ligne suivante.

Voici un exemple :

In [ ]:
# Cette ligne sert à importer la librairie numpy :
import numpy as np
from numpy import linalg

# Je définie une matrice nommée "M_exemple". Vous pouvez donner le nom que vous
# souhaitez à votre matrice. Remarquez que la matrice complète est entre
# crochets.
M_exemple1 = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
M_exemple2 = np.array([
    [1],
    [2],
    [3]
])

# Cette ligne permet d'afficher la matrice "M_exemple"
print("Voici la matrice 1 : \n", M_exemple1)
print("Voici la matrice 2 : \n", M_exemple2)


Voici la matrice 1 : 
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Voici la matrice 2 : 
 [[1]
 [2]
 [3]]


## 2. Élever une matrice à une puissance

* Vous devez utiliser la commande `np.linalg.matrix_power(votre_matrice,votre_puissance)`.

Voici un exemple :

In [ ]:
M_puissance5 = np.linalg.matrix_power(M_exemple1, 5)
print(M_puissance5)

[[232157376 243057312 253957248]
 [420919056 440681472 460443888]
 [609680736 638305632 666930528]]


## 3. Produit de matrices

* Vous devez séparer les deux matrices à multiplier avec l'opérateur `@`.

Voici un exemple :

In [ ]:
produit = M_exemple1 @ M_exemple2
print(produit)

[[ 74]
 [134]
 [194]]


## 4. Calculer un déterminant de matrice


*   Vous devez utiliser la commande `np.linalg.det(votre_matrice)`





In [ ]:
determinant = np.linalg.det(M_exemple1)
print(determinant)

Vous savez maintenant tous les outils nécessaires pour réaliser le laboratoire!

### **Question 1 f)**
Complétez le code suivant pour définir vos matrices $T$ et $P_0$

In [8]:
import numpy as np

T = np.array([
    [0, 0, 0, 1 / 3, 1],
    [1 / 4, 0, 1 / 2, 1 / 3, 0],
    [1 / 4, 1 / 2, 0, 0, 0],
    [1 / 4, 1 / 2, 1 / 2, 0, 0],
    [1 / 4, 0, 0, 1 / 3, 0]
])

print(T)
print(T.shape)

P_0 = np.array([
    [0],
    [1],
    [0],
    [0],
    [0]
])

print(P_0)
print(P_0.shape)

[[0.         0.         0.         0.33333333 1.        ]
 [0.25       0.         0.5        0.33333333 0.        ]
 [0.25       0.5        0.         0.         0.        ]
 [0.25       0.5        0.5        0.         0.        ]
 [0.25       0.         0.         0.33333333 0.        ]]
(5, 5)
[[0]
 [1]
 [0]
 [0]
 [0]]
(5, 1)


### **Question 1 g)**
Définissez votre matrice $P_2$ dans l'environnement.

In [9]:
P_2 = T @ T @ P_0
print(P_2)
print(P_2.shape)

[[0.16666667]
 [0.41666667]
 [0.        ]
 [0.25      ]
 [0.16666667]]
(5, 1)


### **Question 1 h)i)**
Trouvez les matrices $P_{99}$ et $P_{100}$.

In [33]:
P_99 = np.linalg.matrix_power(T, 99) @ P_0
print(P_99)
print(P_99.shape)

P_100 = np.linalg.matrix_power(T, 100) @ P_0
print(P_100)
print(P_100.shape)

P = P_100

[[0.22222222]
 [0.22222222]
 [0.16666667]
 [0.25      ]
 [0.13888889]]
(5, 1)
[[0.22222222]
 [0.22222222]
 [0.16666667]
 [0.25      ]
 [0.13888889]]
(5, 1)


### **Question 1 h)iv)**

Définissez la matrice $A$ dans l'environnement.

In [41]:
# A = np.array([
#     [],
#     [],
#     [],
#     [],
#     []
# ])

A = (T - np.eye(5))

print(A)

[[-1.          0.          0.          0.33333333  1.        ]
 [ 0.25       -1.          0.5         0.33333333  0.        ]
 [ 0.25        0.5        -1.          0.          0.        ]
 [ 0.25        0.5         0.5        -1.          0.        ]
 [ 0.25        0.          0.          0.33333333 -1.        ]]


Vérifiez si la condition pour isoler $P$ est respectée.

In [38]:
print(T - np.eye(5))

[[-1.          0.          0.          0.33333333  1.        ]
 [ 0.25       -1.          0.5         0.33333333  0.        ]
 [ 0.25        0.5        -1.          0.          0.        ]
 [ 0.25        0.5         0.5        -1.          0.        ]
 [ 0.25        0.          0.          0.33333333 -1.        ]]
[[False  True  True False False]
 [False False False False  True]
 [False False False  True  True]
 [False False False False  True]
 [False  True  True False False]]


### **Question 1 h)vii)**
Définissez les matrices $G$ et $B$ dans l'environnement.

In [62]:
G = A.copy()
G[-1, :] = 1

print(G)

B = np.array([
    [0],
    [0],
    [0],
    [0],
    [1]
])

print(B)

[[-1.          0.          0.          0.33333333  1.        ]
 [ 0.25       -1.          0.5         0.33333333  0.        ]
 [ 0.25        0.5        -1.          0.          0.        ]
 [ 0.25        0.5         0.5        -1.          0.        ]
 [ 1.          1.          1.          1.          1.        ]]
[[0]
 [0]
 [0]
 [0]
 [1]]
[[False]
 [False]
 [False]
 [False]
 [False]]


### **Question 1 h)viii)**
Trouvez la matrice $P$ à l'aide des manipulations algébriques appropriée et définissez cette matrice dans l'environnement.

In [63]:
P = (np.linalg.inv(G) @ B)
print(P)

[[0.22222222]
 [0.22222222]
 [0.16666667]
 [0.25      ]
 [0.13888889]]
