# Laboratoire 4
*Préparation au laboratoire*


Dans ce laboratoire, vous aurez besoin de 4 notions en Python :


1.   Définir des matrices
2.   Élever une matrice à une puissance
3.   Effectuer le produit de deux matrices
4. Calculer un déterminant de matrice

Voici des exemples détaillés de ces 3 notions.



## 1. Définir des matrices

*   Vous devez d'abord **importer la librairie numpy**. Nous allons nommer cette librairie np pour simplifier la lecture du code. *Cette action doit être fait une seule fois dans tout le laboratoire.*

* Vous devez ensuite créer votre matrice à l'aide de la commande `np.array`.



Les éléments de la matrice doivent être rentrés ligne par ligne :

*   Tous les éléments d'une ligne doivent se trouver entre crochets "[ ]" et doivent être séparés par une virgule.
*   Pour changer de ligne, il suffit de fermer votre crochet, de séparer à l'aide d'une virgule et d'ouvrir un nouveau crochet pour la ligne suivante.

Voici un exemple :

In [2]:
# Cette ligne sert à importer la librairie numpy :
import numpy as np

# Je définie une matrice nommée "M_exemple". Vous pouvez donner le nom que vous
# souhaitez à votre matrice. Remarquez que la matrice complète est entre
# crochets.
M_exemple1 = np.array([
      [11, 12, 13],
      [21, 22, 23],
      [31, 32, 33]
    ])
M_exemple2 = np.array([
      [1],
      [2],
      [3]
    ])

# Cette ligne permet d'afficher la matrice "M_exemple"
print("Voici la matrice 1 : \n",M_exemple1)
print("Voici la matrice 2 : \n", M_exemple2)


Voici la matrice 1 : 
 [[11 12 13]
 [21 22 23]
 [31 32 33]]
Voici la matrice 2 : 
 [[1]
 [2]
 [3]]


Définissez une matrice nommée Ma_Matrice de dimension 3x3.



## 2. Élever une matrice à une puissance

* Vous devez utiliser la commande `np.linalg.matrix_power(votre_matrice,votre_puissance)`.

Voici un exemple :

In [ ]:
M_puissance5 = np.linalg.matrix_power(M_exemple1,5)
print(M_puissance5)

Élevez votre matrice à définie en 1 à la puissance 4.

## 3. Produit de matrices

* Vous devez séparer les deux matrices à multiplier avec l'opérateur `@`.

Voici un exemple :

In [ ]:
produit = M_exemple1 @ M_exemple2
print(produit)

Effectuez le produit matriciel `M_exemple1` $\cdot$ `Ma_Matrice`.



## 4. Calculer un déterminant de matrice


*   Vous devez utiliser la commande `np.linalg.det(votre_matrice)`





In [ ]:
determinant = np.linalg.det(M_exemple1)
print(determinant)

Calculez le déterminant de votre matrice définie en 1.

Vous savez maintenant tous les outils nécessaires pour réaliser le laboratoire!